@startuml
'https://plantuml.com/class-diagram

class Aufzug
class Aufzugfahrt
class LastenAufzug
class MainGui
class PersonenAufzug
class ViPAufzug

Aufzug <|-- LastenAufzug
Aufzug <|-- PersonenAufzug
Aufzug <|-- ViPAufzug

Aufzug : int Personenzahl
Aufzug : int maxGewicht
Aufzug : int aktuellesStockwerk

LastenAufzug : int qm

PersonenAufzug : boolean Melodie

ViPAufzug : int maxKmh

Aufzugfahrt : String AufzugTyp
Aufzugfahrt : int fahrtGewicht
Aufzugfahrt : int personenZahl
Aufzugfahrt : private int gefahreneStockwerke

@enduml