@startuml
'https://plantuml.com/class-diagram

class Aufzug
class Aufzugfahrt
class LastenAufzug
class MainGui
class PersonenAufzug
class ViPAufzug

Aufzug <|-- LastenAufzug
Aufzug <|-- PersonenAufzug
Aufzug <|-- ViPAufzug

Aufzug : Personenzahl
Aufzug : maxGewicht
Aufzug : aktuellesStockwerk

LastenAufzug : qm

@enduml